name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  misspell:
   # Check if the PR is not from a fork
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout on push
        if: github.event_name == 'push'
        uses: actions/checkout@v2
      - name: Checkout on pull_request
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: reviewdog fixer
        uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          locale: "US"
      - name: sobolevn fixer
        uses: sobolevn/misspell-fixer-action@master
      - uses: peter-evans/create-pull-request@v2.4.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Typos fixes'
          title: "Typos fixes"
          branch: typos
          branch-suffix: timestamp
